-- "การส่งออกรายวัน" (Daily Export) — a document built specifically to deduct
-- StockDEMO, separate from Daily Sales/Shipping. Every row must point at one
-- exact stock_variants row (picked from a live Stock search, not typed as a
-- free-text SKU), so there's never any ambiguity about which size was
-- actually taken out. Run in Supabase SQL editor.

create table if not exists daily_export_rows (
  id bigint generated by default as identity primary key,
  export_date date not null,
  sort_order integer not null default 0,
  stock_variant_id integer not null references stock_variants(id) on delete cascade,
  sku text not null default '',
  size_text text not null default '',
  image_url text,
  qty numeric not null default 1,
  remark text not null default '',
  customer_name text not null default '',
  salesperson text,
  po_no text not null default '',
  stock_deducted_qty numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table daily_export_rows enable row level security;
create index if not exists daily_export_rows_date_idx on daily_export_rows(export_date);
create index if not exists daily_export_rows_variant_idx on daily_export_rows(stock_variant_id);
