// One-off: parses "ใบราคา/price catalog.xlsx" into src/data/price-catalog.ts.
// The sheet is laid out as 3 side-by-side blocks per row (cols 0-3, 5-8, 10-13:
// Model, Image-formula, Size, Price), under category header rows. Re-run this
// and commit the output whenever the source spreadsheet changes.
import * as XLSX from "xlsx";
import { writeFileSync } from "fs";

const SRC = "C:\\Users\\lenovo\\Desktop\\งาน น้อง เจ\\ใบราคา\\price catalog.xlsx";
const OUT = "src/data/price-catalog.ts";

const wb = XLSX.readFile(SRC);
const rows = XLSX.utils.sheet_to_json(wb.Sheets["Sheet1"], { header: 1, raw: false }) as (string | null)[][];

interface Entry {
  sku: string;
  category: string;
  size: string;
  priceLabel: string;
  price: number | null;
}

const entries: Entry[] = [];
let category = "";
// Carries the last-seen SKU per block, for continuation rows that only add
// another size/price option under the same model (blank model cell).
const lastSku = ["", "", ""];

function parsePrice(label: string): number | null {
  const m = label.match(/[\d,]+(\.\d+)?/);
  if (!m) return null;
  const n = Number(m[0].replace(/,/g, ""));
  return Number.isFinite(n) ? n : null;
}

for (const row of rows) {
  if (!row || row.length === 0) continue;

  // Category header: exactly one non-empty cell, in column 0.
  const nonEmpty = row.filter((c) => c != null && String(c).trim() !== "");
  if (nonEmpty.length === 1 && row[0] && String(row[0]).trim() !== "") {
    const text = String(row[0]).trim();
    if (!text.includes("型号") && !text.startsWith("=")) {
      category = text;
      continue;
    }
  }
  if (String(row[0] ?? "").includes("型号")) continue; // column header row

  for (const offset of [0, 5, 10]) {
    const rawSku = row[offset];
    const size = row[offset + 2];
    const priceLabel = row[offset + 3];
    const sku = rawSku != null && String(rawSku).trim() !== "" ? String(rawSku).trim().replace(/\n/g, " ") : "";

    if (sku) lastSku[offset === 0 ? 0 : offset === 5 ? 1 : 2] = sku;
    const effectiveSku = sku || lastSku[offset === 0 ? 0 : offset === 5 ? 1 : 2];

    if (!effectiveSku || !size) continue;
    const sizeText = String(size).trim().replace(/\n/g, " ");
    const priceText = priceLabel != null ? String(priceLabel).trim().replace(/\n/g, " ") : "";
    if (!priceText) continue;

    entries.push({
      sku: effectiveSku,
      category,
      size: sizeText,
      priceLabel: priceText,
      price: parsePrice(priceText),
    });
  }
}

const header = `// Generated by scripts/parse-price-catalog.ts from "ใบราคา/price catalog.xlsx".
// Do not hand-edit — re-run the script and commit the result instead.

export interface PriceCatalogEntry {
  sku: string;
  category: string;
  size: string;
  /** Raw price text from the sheet — some entries are multi-variant and don't reduce to one number. */
  priceLabel: string;
  /** Best-effort numeric price (first amount found in priceLabel), or null if it couldn't be parsed cleanly. */
  price: number | null;
}

export const PRICE_CATALOG: PriceCatalogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(OUT, header, "utf8");
console.log(`Wrote ${entries.length} entries to ${OUT}`);
